"""Theme definitions for LyricView."""

THEME_LIBRARY = {
    "minimal": {
        "name": "minimal",
        "background": "#0a0f1d",
        "panel": "#0f172a",
        "surface": "#111827",
        "current_text_color": "#ffffff",
        "previous_text_color": "#dfe7f5",
        "next_text_color": "#dfe7f5",
        "glow_color": "#ffffff",
        "shadow_color": "#0b1020",
        "font_family": "Segoe UI",
        "font_size": 32,
        "font_weight": "bold",
        "letter_spacing": 0.6,
        "line_height": 1.25,
        "scroll_speed_ms": 2200,
        "pulse_strength": 0.12,
        "animation": "soft-rise",
        "previous_opacity": 0.32,
        "current_opacity": 1.0,
        "next_opacity": 0.42,
        "vertical_offset": 34,
    },
    "deep": {
        "name": "deep",
        "background": "#090d1a",
        "panel": "#121827",
        "surface": "#1f2937",
        "current_text_color": "#ffffff",
        "previous_text_color": "#e9e7ff",
        "next_text_color": "#e9e7ff",
        "glow_color": "#ffffff",
        "shadow_color": "#10091c",
        "font_family": "Segoe UI",
        "font_size": 34,
        "font_weight": "bold",
        "letter_spacing": 0.7,
        "line_height": 1.3,
        "scroll_speed_ms": 2600,
        "pulse_strength": 0.15,
        "animation": "slow-glide",
        "previous_opacity": 0.28,
        "current_opacity": 1.0,
        "next_opacity": 0.38,
        "vertical_offset": 38,
    },
    "aurora": {
        "name": "aurora",
        "background": "#071120",
        "panel": "#12283b",
        "surface": "#17334f",
        "current_text_color": "#ffffff",
        "previous_text_color": "#e5f7ff",
        "next_text_color": "#e5f7ff",
        "glow_color": "#ffffff",
        "shadow_color": "#051a27",
        "font_family": "Segoe UI",
        "font_size": 36,
        "font_weight": "bold",
        "letter_spacing": 0.8,
        "line_height": 1.3,
        "scroll_speed_ms": 2000,
        "pulse_strength": 0.18,
        "animation": "aurora-flow",
        "previous_opacity": 0.26,
        "current_opacity": 1.0,
        "next_opacity": 0.36,
        "vertical_offset": 42,
    },
    "sunset": {
        "name": "sunset",
        "background": "#140b10",
        "panel": "#2d1421",
        "surface": "#431d2b",
        "current_text_color": "#ffffff",
        "previous_text_color": "#fff1f2",
        "next_text_color": "#fff1f2",
        "glow_color": "#ffffff",
        "shadow_color": "#1d0d14",
        "font_family": "Segoe UI",
        "font_size": 33,
        "font_weight": "bold",
        "letter_spacing": 0.7,
        "line_height": 1.25,
        "scroll_speed_ms": 2300,
        "pulse_strength": 0.2,
        "animation": "warm-rise",
        "previous_opacity": 0.3,
        "current_opacity": 1.0,
        "next_opacity": 0.4,
        "vertical_offset": 38,
    },
    "midnight": {
        "name": "midnight",
        "background": "#05070d",
        "panel": "#0f172a",
        "surface": "#141d31",
        "current_text_color": "#ffffff",
        "previous_text_color": "#edf2ff",
        "next_text_color": "#edf2ff",
        "glow_color": "#ffffff",
        "shadow_color": "#090d18",
        "font_family": "Segoe UI",
        "font_size": 38,
        "font_weight": "bold",
        "letter_spacing": 1.0,
        "line_height": 1.35,
        "scroll_speed_ms": 1800,
        "pulse_strength": 0.1,
        "animation": "midnight-lift",
        "previous_opacity": 0.24,
        "current_opacity": 1.0,
        "next_opacity": 0.35,
        "vertical_offset": 44,
    },
    "glass": {
        "name": "glass",
        "background": "#0b1220",
        "panel": "#1e293b",
        "surface": "#263548",
        "current_text_color": "#ffffff",
        "previous_text_color": "#ecfeff",
        "next_text_color": "#ecfeff",
        "glow_color": "#ffffff",
        "shadow_color": "#0f172a",
        "font_family": "Segoe UI",
        "font_size": 31,
        "font_weight": "bold",
        "letter_spacing": 0.5,
        "line_height": 1.2,
        "scroll_speed_ms": 2400,
        "pulse_strength": 0.16,
        "animation": "glass-drift",
        "previous_opacity": 0.33,
        "current_opacity": 1.0,
        "next_opacity": 0.41,
        "vertical_offset": 35,
    },
}


def normalize_theme_name(name: str | None) -> str:
    if not name:
        return "minimal"
    cleaned = name.strip().lower().replace("_", "-").replace(" ", "-")
    return cleaned or "minimal"


def resolve_theme_name(name: str | None) -> str:
    cleaned = normalize_theme_name(name)
    return cleaned if cleaned in THEME_LIBRARY else "minimal"


def get_theme(name: str | None = None) -> dict:
    selected = resolve_theme_name(name)
    theme = dict(THEME_LIBRARY[selected])
    theme["name"] = selected
    return theme
